/**
 * Lahajati Voice Configuration
 * 
 * Complete list of available voices from Lahajati Premium Package 3
 * Total: 329 voices (male, female, and neutral)
 */

export interface LahajatiVoice {
  name: string;
  id_voice: string;
  package: string;
  gender: string; // 1 = male, 2 = female, 3 = neutral/both
}

export const LAHAJATI_VOICES: LahajatiVoice[] = [
  {"name":"رحمة","id_voice":"4ezf4a4fd4gf4erh8ez54dfa4","package":"1","gender":"2"},
  {"name":"حسناء","id_voice":"4ezf4a4fd4gf4erh8ez54dfb01","package":"2","gender":"2"},
  {"name":"وليد","id_voice":"4ezf4a4fd4gf4erh8ez54dfb02","package":"2","gender":"1"},
  {"name":"عائشة","id_voice":"4ezf4a4fd4gf4erh8ez54dfb03","package":"2","gender":"2"},
  {"name":"مهند","id_voice":"4ezf4a4fd4gf4erh8ez54dfb04","package":"2","gender":"1"},
  {"name":"يمنى","id_voice":"4ezf4a4fd4gf4erh8ez54dfb05","package":"2","gender":"2"},
  {"name":"نورة","id_voice":"4ezf4a4fd4gf4erh8ez54dfb06","package":"2","gender":"2"},
  {"name":"عارف","id_voice":"4ezf4a4fd4gf4erh8ez54dfb07","package":"2","gender":"1"},
  {"name":"أكرم","id_voice":"4ezf4a4fd4gf4erh8ez54dfb08","package":"2","gender":"1"},
  {"name":"أمين","id_voice":"4ezf4a4fd4gf4erh8ez54dfb09","package":"2","gender":"1"},
  {"name":"فهد","id_voice":"4ezf4a4fd4gf4erh8ez54dfb0a","package":"2","gender":"1"},
  {"name":"بهاء","id_voice":"4ezf4a4fd4gf4erh8ez54dfb0b","package":"2","gender":"1"},
  {"name":"ناجا","id_voice":"4ezf4a4fd4gf4erh8ez54dfb0c","package":"2","gender":"2"},
  {"name":"عازم","id_voice":"4ezf4a4fd4gf4erh8ez54dfb0d","package":"1","gender":"1"},
  {"name":"ماجد","id_voice":"4ezf4a4fd4gf4erh8ez54dfb0e","package":"2","gender":"1"},
  {"name":"علي","id_voice":"4ezf4a4fd4gf4erh8ez54dfb0f","package":"2","gender":"1"},
  {"name":"فرح","id_voice":"4ezf4a4fd4gf4erh8ez54dfb10","package":"1","gender":"2"},
  {"name":"ابتسام","id_voice":"4ezf4a4fd4gf4erh8ez54dfb11","package":"2","gender":"2"},
  {"name":"باسم","id_voice":"4ezf4a4fd4gf4erh8ez54dfb12","package":"2","gender":"1"},
  {"name":"كرم","id_voice":"4ezf4a4fd4gf4erh8ez54dfb13","package":"2","gender":"1"},
  {"name":"موسى","id_voice":"4ezf4a4fd4gf4erh8ez54dfb14","package":"1","gender":"1"},
  {"name":"أسماء","id_voice":"4ezf4a4fd4gf4erh8ez54dfb15","package":"2","gender":"2"},
  {"name":"زكية","id_voice":"4ezf4a4fd4gf4erh8ez54dfb16","package":"2","gender":"2"},
  {"name":"بهجت","id_voice":"4ezf4a4fd4gf4erh8ez54dfb17","package":"1","gender":"1"},
  {"name":"هنادي","id_voice":"4ezf4a4fd4gf4erh8ez54dfb18","package":"1","gender":"2"},
  {"name":"نصير","id_voice":"4ezf4a4fd4gf4erh8ez54dfb19","package":"2","gender":"1"},
  {"name":"بدر","id_voice":"4ezf4a4fd4gf4erh8ez54dfb1a","package":"1","gender":"1"},
  {"name":"جابر","id_voice":"4ezf4a4fd4gf4erh8ez54dfb1b","package":"1","gender":"1"},
  {"name":"منيرة","id_voice":"4ezf4a4fd4gf4erh8ez54dfb1c","package":"1","gender":"2"},
  {"name":"خولة","id_voice":"4ezf4a4fd4gf4erh8ez54dfb1d","package":"1","gender":"2"},
  {"name":"سامر","id_voice":"JXOWwj01GoJ4dl11OrqJ9HDl","package":"2","gender":"1"},
  {"name":"كريم","id_voice":"cj2WY5KAnc6cICegueOkLs5N","package":"2","gender":"1"},
  {"name":"وسيم","id_voice":"1k8WtsIWsDqI3C9baWp0dsMG","package":"2","gender":"1"},
  {"name":"أمير","id_voice":"7YNpaX4V0erPgvQOb5ZEGZLH","package":"2","gender":"1"},
  {"name":"جاسم","id_voice":"OZ9DqbY2l7qcPqdC83YhclWW","package":"2","gender":"1"},
  {"name":"حمزة","id_voice":"RAoOTRLqoeDJdOgXLdP2Dx67","package":"2","gender":"1"},
  {"name":"عمر","id_voice":"PccMhXg14THP5pXhbUBkIA8W","package":"2","gender":"1"},
  {"name":"جميلة","id_voice":"HjNfZdwQJdwoWdkL54I6Z6Xv","package":"2","gender":"2"},
  {"name":"ناديا","id_voice":"0mSjbpx22sNgYYBx7uH5OSmq","package":"2","gender":"2"},
  {"name":"ثامر","id_voice":"zOaBgbbZvyEgv14QRBTNmgrF","package":"2","gender":"1"},
  {"name":"أحلام","id_voice":"Fpxh0vFCpKSDzIlubZnCkKEz","package":"2","gender":"2"},
  {"name":"غانم","id_voice":"LW84zLz6N3Pijvwj67vTdxAY","package":"2","gender":"1"},
  {"name":"أدهم","id_voice":"XnU3bCtXNMie17HoYbmIvy5f","package":"2","gender":"2"},
  {"name":"أسر","id_voice":"I4vU237Hg7xs1ohv12YBJ9NH","package":"2","gender":"1"},
  {"name":"تامر","id_voice":"8d14CVcHAPfQVYN1mgG6wsBS","package":"2","gender":"1"},
  {"name":"رافي","id_voice":"hkz6UpxcTjV7v1pV9xI1zT9Q","package":"2","gender":"1"},
  {"name":"ساجي","id_voice":"N7hsd3rTOeWGfCA2z3s3Vork","package":"2","gender":"1"},
  {"name":"فارس","id_voice":"ibnSq09BWzJ6MTIW8lQeAHfH","package":"2","gender":"1"},
  {"name":"عنان","id_voice":"A9w15QSxYou8M5RYbwTkQu51","package":"2","gender":"1"},
  {"name":"خديجة","id_voice":"06DIgDY2jFDqK35MAjXC7Mxn","package":"2","gender":"2"},
  {"name":"ماجد","id_voice":"7SXaZFHBS9mDSHUZDcRUbif3","package":"2","gender":"1"},
  {"name":"أيمن","id_voice":"jJSESarxjPPPKI4YhJE144AN","package":"2","gender":"1"},
  {"name":"يزد","id_voice":"aWOdE1VHRKxx2xycvj4qL7KP","package":"2","gender":"1"},
  {"name":"ناصر","id_voice":"0tw3GzB1S6J2r0gMQYUeRKrD","package":"2","gender":"1"},
  {"name":"زكرياء","id_voice":"bAneWYK44t7ihGVXQR1uKo2H","package":"2","gender":"1"},
  {"name":"سنان","id_voice":"9uFDFoSszIqG9Ud5WYXiRewG","package":"2","gender":"3"},
  {"name":"حمود","id_voice":"BM4lMwQODkq3c3IHeiU1yh6q","package":"2","gender":"1"},
  {"name":"رضوان","id_voice":"jfek5XgEmuHRmSdnWVnviRhe","package":"2","gender":"1"},
  {"name":"زيد","id_voice":"ojxtxkEQ9M5qLtVXbk40BkK6","package":"2","gender":"1"},
  {"name":"أنور","id_voice":"cgUalo6DRqsFKhx91e6qSFHr","package":"2","gender":"1"},
  {"name":"قيس","id_voice":"jdTyLMhOJfqCeNNN4f2SgQnv","package":"2","gender":"3"},
  {"name":"نواف","id_voice":"M4ioUBA4T11C6y8IF7xeBWoP","package":"2","gender":"1"},
  {"name":"جواد","id_voice":"TwYyQYQrREayD6mn4BbPxpUO","package":"2","gender":"1"},
  {"name":"إسلام","id_voice":"3MJrX4GuwDPrUKapfNyyyo8d","package":"2","gender":"1"},
  {"name":"أماني","id_voice":"uFqRj5LmxOcqbPg4qjyt4nvb","package":"2","gender":"2"},
  {"name":"آمنة","id_voice":"Y1xQkHexQY1quXCQtVRxqgMM","package":"2","gender":"2"},
  {"name":"كمال","id_voice":"zim4mMRf4dpq8NYIsPOo4pkE","package":"2","gender":"1"},
  {"name":"بديعة","id_voice":"tLH9wXh1rTN48S2HpCNOKddv","package":"2","gender":"2"},
  {"name":"لطفي","id_voice":"hBosVkDq2NB5R0CeBzwxgra8","package":"2","gender":"1"},
  {"name":"بيسان","id_voice":"4Ryv2vWhbEVgZLPomfoS3AOm","package":"2","gender":"2"},
  {"name":"أسمى","id_voice":"Je2JwhbNVpj21AfheuH7jKmg","package":"2","gender":"2"},
  {"name":"مصطفى","id_voice":"W0EhEHBh7e8jF9LMQ5MSZJKO","package":"2","gender":"1"},
  {"name":"منصور","id_voice":"SVPTclywWSXOEDM7F46WbXkv","package":"2","gender":"1"},
  {"name":"محمد","id_voice":"ia8KQUBLv4UE4ac2XRnWu4lY","package":"2","gender":"3"},
  {"name":"زاهر","id_voice":"sXPiIuLxadWNEuo5MVWzCyJt","package":"2","gender":"1"},
  {"name":"أجوان","id_voice":"CHWhatRHwYVGVJljb18R5Rmu","package":"2","gender":"2"},
  {"name":"أحمد","id_voice":"ZR8Sgn7gLiInfvLVLi2nWVVn","package":"2","gender":"1"},
  {"name":"معتز","id_voice":"LSxcnhfFIMpGZEAxS4mWIdkp","package":"2","gender":"1"},
  {"name":"هاجر","id_voice":"yblIngbyi5Jk6Om3XiNmF6pm","package":"2","gender":"3"},
  {"name":"هند","id_voice":"g7HZARsR8PSQDesXmFtgTYK8","package":"2","gender":"3"},
  {"name":"إيمار","id_voice":"frk5ddwEnZ9gSJGSCXYX05o6","package":"2","gender":"3"},
  {"name":"إلهام","id_voice":"y4e8CYWVhNAFMxzNamFGZOlx","package":"2","gender":"3"},
  {"name":"يسرى","id_voice":"XdOCjVo1Cnwdjp5gmT1zP2eo","package":"2","gender":"3"},
  {"name":"لُجين","id_voice":"gNKpwHTAprDubqwWARQnhzPP","package":"2","gender":"3"},
  {"name":"لميس","id_voice":"yMKDyhOMLhtARw1v6rGANcLr","package":"2","gender":"3"},
  {"name":"همس","id_voice":"6wRRidlZD51i1q9PlGr9gVEz","package":"2","gender":"3"},
  {"name":"فهمي","id_voice":"CFEdzvcRZFEAffECeg77Be","package":"2","gender":"1"},
  {"name":"رعد","id_voice":"9cWd6cOEvvo6ygqIMlYExruV","package":"2","gender":"1"},
  {"name":"بدري","id_voice":"KG3nB9Uerp6mvQYy99XzWB7P","package":"2","gender":"1"},
  {"name":"فواز","id_voice":"fhHVZMbBoaYpudLq8BSLeTSC","package":"2","gender":"1"},
  {"name":"يزيد","id_voice":"q4kpVOGTRD4uK5Bb4yuCLwaO","package":"2","gender":"1"},
  {"name":"مروان","id_voice":"T2oM637uDSGVqXFEBIc9ZorC","package":"2","gender":"1"},
  {"name":"جمال","id_voice":"NeUZ15z4ew7V7rlQPZNYKXFn","package":"2","gender":"1"},
  {"name":"ياسر","id_voice":"WAB3JTQkuAjYyOrUNvBtVLuo","package":"2","gender":"1"},
  {"name":"إدريس","id_voice":"aw8V1jsAeXZfxAouAmHtZzzK","package":"2","gender":"1"},
  {"name":"عزام","id_voice":"6WiHJ2vAScwPBNwwX424Bcl7","package":"2","gender":"1"},
  {"name":"هاني","id_voice":"Yt0cmihZMXa10rf1TB6tuNfG","package":"2","gender":"1"},
  {"name":"لؤي","id_voice":"WP0oR9mF0veQUjed9p1zdhL6","package":"2","gender":"1"},
  {"name":"سليم","id_voice":"myGnldICDUroIpRdwd15O8iF","package":"2","gender":"1"},
  {"name":"قحطان","id_voice":"XhOxe2o1kFikmX38iPVjKjP4","package":"2","gender":"1"},
  {"name":"بلال","id_voice":"vVYeV1ku67e2VU218rKQY5i4","package":"2","gender":"1"},
  {"name":"يوسف","id_voice":"MGr9pUc1UBhMOkgh5lp4VKFL","package":"2","gender":"1"},
  {"name":"رانية","id_voice":"ukxlPk5CC7QFdyXBLfUcjNFE","package":"2","gender":"2"},
  {"name":"صفية","id_voice":"dPzDbZKiiuv9Xx0WpO2t5UPI","package":"2","gender":"2"},
  {"name":"صهيب","id_voice":"Jz7bgbPX7EqDJDrlAbdBUkQq","package":"2","gender":"1"},
  {"name":"برهان","id_voice":"NyyQWAJH2D9YCqq0vCtkbZg3","package":"2","gender":"1"},
  {"name":"خالد","id_voice":"kixO1D1Uw1kfcEbizhfBOUqz","package":"2","gender":"1"},
  {"name":"جهيد","id_voice":"WM4z4hg7AFTwCO4kR88NNKZp","package":"2","gender":"1"},
  {"name":"شادي","id_voice":"28RjgjIljV5C3UmrduV9uLny","package":"2","gender":"3"},
  {"name":"إياد","id_voice":"A7bRrPMthMuu7vJWdJjyRTEO","package":"2","gender":"1"},
  {"name":"سفيان","id_voice":"JeIbBK2PDTMpOQHkHfuxhiup","package":"2","gender":"1"},
  {"name":"حنان","id_voice":"HThr0oyxeEXcNp3dSQW5pNdE","package":"2","gender":"2"},
  {"name":"محسن","id_voice":"TYHoRsSAYoVCLuqevsca3v87","package":"2","gender":"1"},
  {"name":"أيهم","id_voice":"YLCYKk1vrz4ikod0JjVtR44a","package":"2","gender":"1"},
  {"name":"عامر","id_voice":"LqjuNBiYlMsohfBOkmMHDrWG","package":"2","gender":"1"},
  {"name":"جلال","id_voice":"DNPpR1DbDsuDDsEid3SsMXjl","package":"2","gender":"1"},
  {"name":"خلود","id_voice":"5q6nwGbgf6NW2e5Ye2sGcJjk","package":"2","gender":"2"},
  {"name":"رياض","id_voice":"02ExhwRAmBHuPN5q5poRHubX","package":"2","gender":"1"},
  {"name":"صالح","id_voice":"kUM44ObSKprqgIsmPoI036UK","package":"2","gender":"1"},
  {"name":"أنيس","id_voice":"u5QdsTZS3EymT1OjUCkKm3Tj","package":"2","gender":"1"},
  {"name":"عادل","id_voice":"mTaUUqafXMi7uq6iTj2WzAR4","package":"2","gender":"1"},
  {"name":"جمعون","id_voice":"Bkzu5e61e3C9uKiFaijclL2H","package":"2","gender":"1"},
  {"name":"حميد","id_voice":"ywGQkM1RF6KtHwSvChSsX5d9","package":"2","gender":"1"},
  {"name":"روان","id_voice":"1tAEavy0K3Gnsgr5ZGk1coHQ","package":"2","gender":"2"},
  {"name":"جليل","id_voice":"dJvAYMv3PAKrpv0bZD3p7Sow","package":"2","gender":"1"},
  {"name":"منال","id_voice":"PVToN3ZtUYZF0BN81nc9u4qW","package":"2","gender":"2"},
  {"name":"عمار","id_voice":"5oDGYWujlmy70V4YJKu0bFqu","package":"2","gender":"1"},
  {"name":"يحيى","id_voice":"arBxPSg9qM5Uq0CrBI1pty4c","package":"2","gender":"1"},
  {"name":"عبد الله","id_voice":"53pENDfFoVvJaukQtPtfDrcd","package":"2","gender":"1"},
  {"name":"فاطمة","id_voice":"rBkkwYhhctGrbaLyilv0NGUU","package":"2","gender":"2"},
  {"name":"جهاد","id_voice":"PuJKc5ye9GQ4EZeuYL6oMtev","package":"2","gender":"1"},
  {"name":"بكر","id_voice":"fo52ijNsXkhVyZViFSLTesdq","package":"2","gender":"1"},
  {"name":"ريان","id_voice":"UcTIWaotrhidxc6DsSPXwNgT","package":"2","gender":"3"},
  {"name":"ريم","id_voice":"HUyd8aPbKaTsEvwUILvZTqXS","package":"2","gender":"2"},
  {"name":"أية","id_voice":"3W8ymPRhDyFUnPmbHBVTQmke","package":"2","gender":"3"},
  {"name":"زين","id_voice":"O7cZYCAxxz27CkDdNxt1BtP2","package":"2","gender":"3"},
  {"name":"بادي","id_voice":"ivMoXOi8OYrJJx3e53LCuX0m","package":"2","gender":"1"},
  {"name":"حازم","id_voice":"qcu3M8qLBjkbLRfMODY5Fdoc","package":"2","gender":"1"},
  {"name":"عمر","id_voice":"kiVxaF5gjN4jeAhC9gORGQQd","package":"2","gender":"1"},
  {"name":"بوجمعة","id_voice":"3WIpyNmVYab8rCHxEPHUpH5w","package":"2","gender":"1"},
  {"name":"رقية","id_voice":"8QJsyDBKVDlDUTWClgQwIOkV","package":"2","gender":"2"},
  {"name":"حنين","id_voice":"sesFrSB9EC0LmZ8qXYSmEclh","package":"2","gender":"2"},
  {"name":"عزيز","id_voice":"EX7tfvAkCV5alJpZKEVTVCql","package":"2","gender":"1"},
  {"name":"ركان","id_voice":"5wmjenHfVeln8XRgz3gIGJnI","package":"2","gender":"1"},
  {"name":"مروة","id_voice":"Em2xqesyF6QBOhsHltowqRin","package":"2","gender":"1"},
  {"name":"منير","id_voice":"ZZ4zGL3rzIJU51VdUetex20s","package":"2","gender":"1"},
  {"name":"حسان","id_voice":"Zr0FkEHV5nicbBShDUPv4Z75","package":"2","gender":"1"},
  {"name":"أمجد","id_voice":"fRYaFkW1VBIon8odqV7PZtlV","package":"2","gender":"3"},
  {"name":"جهان","id_voice":"uciiTVFSQQWUoLampsKR4at4","package":"2","gender":"2"},
  {"name":"خيرة","id_voice":"f4xYVmeDLM5VF8pxEcoKQvQZ","package":"2","gender":"2"},
  {"name":"عاصم","id_voice":"0PAMD3qWgZxQ2mnZaL4lC06c","package":"2","gender":"3"},
  {"name":"فؤاد","id_voice":"BWjFZvhrv3gff0EzMgfttyU2","package":"2","gender":"1"},
  {"name":"مراد","id_voice":"O8N0I6vRx38laA0x7ATvD2Fx","package":"2","gender":"1"},
  {"name":"عاشور","id_voice":"ZLhpXuB6EBza0bsPP0Q8Hwj3","package":"2","gender":"1"},
  {"name":"منتصر","id_voice":"UyaqWkmRRe8xJDrYO8K9PGyO","package":"2","gender":"1"},
  {"name":"جورج","id_voice":"t4on9UfRXFktS2K5t5ayoUW6","package":"2","gender":"1"},
  {"name":"كلثوم","id_voice":"vx9cdqj6acodOC55tJhDiNGd","package":"2","gender":"2"},
  {"name":"مجد","id_voice":"pxJqHoo0qtrJxTQrh7TIAP0y","package":"2","gender":"1"},
  {"name":"عزون","id_voice":"vyZbhj58MdfwC4mzOeEGfGAY","package":"2","gender":"3"},
  {"name":"عمروش","id_voice":"4dSFohMYnRgwvOqp4b2ZIZYe","package":"2","gender":"3"},
  {"name":"شمس","id_voice":"Q6agE1Hfuo5tevd4YJcSAIjZ","package":"2","gender":"3"},
  {"name":"سيف","id_voice":"Z0d9MEweke2he8ycEUPnZr1u","package":"2","gender":"3"},
  {"name":"زهرة","id_voice":"3GMrhm1mtKTBXX8cR68k8pkE","package":"2","gender":"3"},
  {"name":"ريمي","id_voice":"h8DwTFfUNkjw05vQ0UeglC04","package":"2","gender":"3"},
  {"name":"ضياء","id_voice":"PWbgwREabLcziWZ37fMf7vRh","package":"2","gender":"3"},
  {"name":"عيسى","id_voice":"SAm9x0bWEOFch36Yx7faZgH1","package":"2","gender":"3"},
  {"name":"فادي","id_voice":"hZM2p3lUZvUKqVxtbNB2UUIM","package":"3","gender":"1"},
  {"name":"جودي","id_voice":"V7mabUEyDDVVRRZ2cTEIANRK","package":"2","gender":"2"},
  {"name":"حسين","id_voice":"l6ErPsa0knOuPHhg7QtW3zyr","package":"2","gender":"1"},
  {"name":"أنفال","id_voice":"t3FBpikRDUVJuEgd6AF0mepb","package":"2","gender":"3"},
  {"name":"حيدر","id_voice":"FpNMNF9wDGSPCgmZyX14zAbl","package":"3","gender":"3"},
  {"name":"طاهر","id_voice":"W5K3PDGOE0asuiOBoxUFFwWa","package":"3","gender":"1"},
  {"name":"جعفر","id_voice":"ZRXAk0gDIStVdb5phyfMP6hG","package":"3","gender":"1"},
  {"name":"فريد","id_voice":"CMtLBn1kI6nJ3xxChDljHPTY","package":"3","gender":"3"},
  {"name":"زمرد","id_voice":"2lH82cmAUHNLINhS9606sTms","package":"2","gender":"2"},
  {"name":"مجيد","id_voice":"mQU1fi1vNQ5Irln56Dzqvd5o","package":"2","gender":"1"},
  {"name":"بركان","id_voice":"o1e5CXnQukphz3Mgj3ITbpZ1","package":"2","gender":"1"},
  {"name":"مؤيد","id_voice":"3ZRQTENvLtzzLD0GfwwucBH9","package":"2","gender":"1"},
  {"name":"كريمة","id_voice":"LJqja4TqHfapKXlVMteC0SzU","package":"2","gender":"2"},
  {"name":"شاهين","id_voice":"VeuVcVMv3Njkrbi9lbKAAcfr","package":"2","gender":"1"},
  {"name":"توفيق","id_voice":"xdLNidZF2WEyaz4zSDk9AHNK","package":"2","gender":"1"},
  {"name":"حميدة","id_voice":"o610oNVWpF0LUMs6WJpGsGz4","package":"2","gender":"1"},
  {"name":"ميدو","id_voice":"Jr21YtzcRXVUzoOK21t0t5L4","package":"2","gender":"1"},
  {"name":"جبين","id_voice":"8uxuaPEZN44Gw7g65pSFtjzh","package":"2","gender":"3"},
  {"name":"جادر","id_voice":"BemgcGxcvnuvNhl8Tvy61O08","package":"2","gender":"1"},
  {"name":"جنين","id_voice":"h5L6m4fiPeGgkswZGH5F1tkS","package":"2","gender":"2"},
  {"name":"مازن","id_voice":"nnczFqaC9dDYUyfXQqBA8Zxo","package":"2","gender":"1"},
  {"name":"أبان","id_voice":"qllMr5XUw0BRuIRcUhZIgTaG","package":"2","gender":"3"},
  {"name":"شروق","id_voice":"1ExBbF5CeBTH7tuKokwlpLjO","package":"3","gender":"2"},
  {"name":"حياة","id_voice":"EvVFOdxoN3m96zpE6mhBj12R","package":"3","gender":"2"},
  {"name":"رماح","id_voice":"ymDlgOND4pex6du54WnlWKkq","package":"3","gender":"1"},
  {"name":"إحسان","id_voice":"zHrtlFLebisOVcF6VxaR7NPg","package":"3","gender":"2"},
  {"name":"جود","id_voice":"xRR9QFAJmMy8gRB9raDwbTu9","package":"3","gender":"2"},
  {"name":"قاسم","id_voice":"UxNbpi2tQQhLOpHVGbArx3Fr","package":"3","gender":"1"},
  {"name":"بيان","id_voice":"rChAQ6m29hrEnePzbMvZ9pUR","package":"3","gender":"1"},
  {"name":"خاسف","id_voice":"z8WvM4oolpYoCKY5Df3ht2z9","package":"3","gender":"1"},
  {"name":"جيهان","id_voice":"D0CFfj3QmAhXuuyvGQWTv6MR","package":"3","gender":"2"},
  {"name":"رامي","id_voice":"HgCtYZYvJYzejEIZBNkSHIwO","package":"3","gender":"1"},
  {"name":"نصري","id_voice":"Znrz6KRKItzr2IADRinrINym","package":"3","gender":"1"},
  {"name":"حكيم","id_voice":"CwqxAqINVkaNFLZNUrmybxer","package":"3","gender":"1"},
  {"name":"سلاف","id_voice":"4IHIQuG15pScch6Sqj9lqk8M","package":"3","gender":"2"},
  {"name":"نورس","id_voice":"AlZYt0V7ac9WUQsmt3Su3UkH","package":"3","gender":"1"},
  {"name":"مشاري","id_voice":"plxjuecQzNXcPVXdYqpV5epZ","package":"3","gender":"1"},
  {"name":"شريف","id_voice":"MurBmeCqaPQWw8RZySCYCRI0","package":"3","gender":"1"},
  {"name":"إلياس","id_voice":"Ttc4U6IPzI21GKSJyz4IRQkx","package":"3","gender":"3"},
  {"name":"زهير","id_voice":"5HZ2OZBdHX8wsj3M7GnHhLk3","package":"3","gender":"3"},
  {"name":"سعاد","id_voice":"TL0GMPZEMs3HHJJp0uyUFvhQ","package":"3","gender":"2"},
  {"name":"سمير","id_voice":"TD0K3wOXclaARbwdKKMmdduX","package":"3","gender":"1"},
  {"name":"عاطف","id_voice":"hGU9iHjaPvz2zRcJ5LROlDUU","package":"3","gender":"1"},
  {"name":"أمينة","id_voice":"9nEQXEQ2WrMxspdabyHthlJX","package":"3","gender":"2"},
  {"name":"مريم","id_voice":"1MndTCp2Kg8zIyYSZUquo1yS","package":"3","gender":"2"},
  {"name":"جمانة","id_voice":"eM6d7S3kkJvDamFvDBbEqKHu","package":"3","gender":"2"},
  {"name":"معاذ","id_voice":"qNXN3vmNKHpRnwzyqLbWgM0K","package":"3","gender":"1"},
  {"name":"صابر","id_voice":"B5nwFUdG2VHoWYneId5rM8x5","package":"3","gender":"1"},
  {"name":"زيدان","id_voice":"1A35m7qJIYPfmUyGSPPuf3lY","package":"3","gender":"1"},
  {"name":"زينب","id_voice":"Sq0RzUzwZannjlWFRj5BR6Ta","package":"3","gender":"2"},
  {"name":"إكرام","id_voice":"T1KxX5IdqVYsTaKC0GyH9JsL","package":"3","gender":"2"},
  {"name":"بثينة","id_voice":"7FIhNczooWzVsY36a16Evmjp","package":"3","gender":"2"},
  {"name":"سهام","id_voice":"1PtzOa1tm6xYQ4ZeDKhgGkAx","package":"3","gender":"2"},
  {"name":"خيمة","id_voice":"oCSNpl3Ddt6nV1J3ha3x5SNk","package":"3","gender":"2"},
  {"name":"عبير","id_voice":"6Op8UKxwI34ajaOgxeBBwFBC","package":"3","gender":"2"},
  {"name":"مسعود","id_voice":"WnLw40wGQ1qOrTmGnFZ3r7cJ","package":"3","gender":"1"},
  {"name":"رضا","id_voice":"EHKypcvv7VL2i2IyUou0byga","package":"3","gender":"1"},
  {"name":"فوزي","id_voice":"MONO8zEBWoPcGYFwBrXj5xdV","package":"3","gender":"1"},
  {"name":"ضرغام","id_voice":"4C9dh8bk5h18GhWDylGDu29W","package":"3","gender":"1"},
  {"name":"أمال","id_voice":"8YnqUYo99C5DOfxNAaNeiTdP","package":"3","gender":"2"},
  {"name":"حمودي","id_voice":"ZeMjtig21NF9rqIdXMR5kJEz","package":"3","gender":"1"},
  {"name":"سمية","id_voice":"exU4QoH2V718qbUweBRRuRcE","package":"3","gender":"2"},
  {"name":"غاني","id_voice":"ymGX68MnJfbZbGv3GU2rmTmJ","package":"3","gender":"1"},
  {"name":"نورهان","id_voice":"WUrWgg7ECPzywZpEnSiLK8mc","package":"3","gender":"2"},
  {"name":"سماح","id_voice":"zTr5psK8O5ySfpjjxIQqHsuY","package":"3","gender":"2"},
  {"name":"نريمان","id_voice":"TRwYE8ToMjuUN0dEekXNz10v","package":"3","gender":"2"},
  {"name":"نورية","id_voice":"i0SmCbG4sYi2cCBkK0RaA4PH","package":"3","gender":"2"},
  {"name":"هيثم","id_voice":"9Jql0rG4MYQ18Gh0hPiFSyqr","package":"3","gender":"1"},
  {"name":"حسون","id_voice":"Cw3evEg5mJWDHLK5TLy0Q5uG","package":"3","gender":"1"},
  {"name":"مرموش","id_voice":"vyrOpPB0r47sJ54qSq1UZbQT","package":"3","gender":"1"},
  {"name":"حفيظة","id_voice":"pOYsJfZGCXLvWazGAnUb9WPv","package":"3","gender":"2"},
];

/**
 * Get a random voice from the available voices
 * Optionally filter by gender or package
 */
export function getRandomLahajatiVoice(options?: {
  gender?: "1" | "2" | "3"; // 1=male, 2=female, 3=neutral
  package?: "1" | "2" | "3";
}): LahajatiVoice {
  let voices = LAHAJATI_VOICES;

  // Filter by gender if specified
  if (options?.gender) {
    voices = voices.filter((v) => v.gender === options.gender);
  }

  // Filter by package if specified
  if (options?.package) {
    voices = voices.filter((v) => v.package === options.package);
  }

  // Return random voice from filtered list
  const randomIndex = Math.floor(Math.random() * voices.length);
  return voices[randomIndex];
}
